### PR TITLE
Fluent Interface for attributes

### LINKED ISSUE #132: Return $this in Vertex::setAttribute
How about return $this value in 
https://github.com/clue/graph/blob/master/src/Vertex.php#L380
(fluent interface) ?

### PR DESCRIPTION
**Pull request by jmauerhan**
Updated multiple classes that use the setAttribute and removeAttribute methods, and their tests.

Closes #132

### CODE REVIEW

**Comment by jmauerhan** [comment]
Took me a few tries, but I found them all I think :) Tests passing.

**Comment by clue** [comment]
Sorry I didn't get back to this earlier, but the changes LGTM and I'd love to (finally) get this in! :shipit: 

May I ask you to squash your commits? :+1:

**Comment by jmauerhan** [comment]
I'm not sure how to, but I think you can do it when you merge the PR, right?

**Comment by clue** [comment]
> I'm not sure how to […]

No problem, perhaps the following two links may help? :+1: 

* https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/
* https://davidwalsh.name/squash-commits-git

> […] but I think you can do it when you merge the PR, right?

GitHub does not allow one to squash multiple commits and then merge. My only option would be to squash locally and then open a new PR and thus close this one, so this isn't particularly appealing :)

**Comment by jmauerhan** [comment]
Weird, when I merge PRs for work, github gives me the option to merge as one commit. 

I'll see if I can still do it here. Thanks :)

**Comment by jmauerhan** [comment]
I no longer have the graph repo forked in my own account (sorry, this is really old lol)

**Comment by jmauerhan** [comment]
https://github.com/blog/2141-squash-your-commits

For the record, yes, you as the maintainer can do this. I tried moving the changes into a new checkout of the repo, and must have missed something. I suggest you do it, since this one was passing.

I also can't re-open, so hopefully you see this.

**Comment by clue** [comment]
> GitHub does not allow one to squash multiple commits and then merge

GitHub only allows one to squash the complete branch onto the master branch or merge the whole branch. Unfortunately, it does not allow one to squash a whole branch and then merge it into the master branch. This is what I've been suggesting you to do, as it requires manual instructions as per the above links.

No worries if you're not familiar with the idiosyncrasies of git, I can do this myself, but expect this to take some time until I get to this :+1: 

> I also can't re-open, so hopefully you see this.

Looks like GitHub doesn't recognize your fork anymore because it's been deleted in the meantime.

**Comment by jmauerhan** [comment]
Sounds good!

**Comment by jkuchar** [comment]
Don't you want to make composition which provides fluent interface? This breakd encaptulation - [more](https://ocramius.github.io/blog/fluent-interfaces-are-evil/)

**Comment by clue** [comment]
@jkuchar I think this is a valid concern, this PR tries to implement #132, let's move the discussion over there? :)

**Comment by jkuchar** [comment]
Sure.

**Pull request closed without merging**
