### PR TITLE
#135 - Added removeAttribute method

### LINKED ISSUE #135: ability to remove edge attributes
At the moment you can add and update edge attributes but there's no possibility for removing an edge attribute at a later time. Neither the `Edge`-classes nor the `AttributeBag`-classes provide functionality to delete attributes.

The same is true for `Vertex` objects.

### PR DESCRIPTION
**Pull request by johnathanmdell**
Added ability to remove attributes

Closes #135

### CODE REVIEW

**Comment by clue** [comment]
Thanks for this PR @johnathanmdell, the changes LGTM! :+1: 

Issue #135 and this PR description only mentions *removing attributes*, but the changeset also includes a `hasAttribute()` method.

I'm :+1: on getting the `removeAttribute()` method in, but I'm undecided about the current state of the `hasAttribute()`. In particular, how should we take `null` values into account? See also #103 for some background.

We *can* look into working this out now, but I'm also okay with postponing this for a future PR.

What's your take on this?

**Comment by johnathanmdell** [comment]
The hasAttribute was purely habit, good point on the on the null value, I'm happy with removing it for the current PR.

**Comment by johnathanmdell** [comment]
@clue PR updated

**Comment by clue** [comment]
Thanks @johnathanmdell, merged via #138!

**Pull request closed without merging**
